### ISSUE TITLE
Error with the latest update

### ISSUE THREAD

**Issue by JonoHaysom** [torifat/xiaomi-mi-air-purifier#231] opened 2021-11-22 05:53 UTC
I'm on the latest plugin version. my logs show the below errors. I'm on 1.3.4 for Homebridge too

my Node JS and NPM version
Node.js Version	v14.16.0
Npm Version	v6.14.11

[11/22/2021, 9:50:29 AM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Cannot read property 'value' of undefined. See https://git.io/JtMGR for more info.
[11/22/2021, 9:50:29 AM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Cannot read property 'value' of undefined. See https://git.io/JtMGR for more info.
[11/22/2021, 9:50:29 AM] [homebridge-xiaomi-mi-air-purifier] This plugin generated a warning from the characteristic 'PM2.5 Density': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[11/22/2021, 9:50:29 AM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read property 'value' of null. See https://git.io/JtMGR for more info.
[11/22/2021, 9:50:29 AM] [homebridge-xiaomi-mi-air-purifier] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.

**Comment by torifat** [comment] 2021-11-22 13:05
Duplicate of #229. Please follow the update there.

**Closed by torifat** 2021-11-22 13:05 UTC

**Comment by frasfs** [comment] 2021-12-03 12:45
@torifat Hi there, can you please explain how to fix the issue? I have went to the duplicate #229 but you only posted codes and usage with no explanation as to what to do with the codes. Can you please add instructions as I have an error same as mentioned above.

**Comment by torifat** [comment] 2021-12-03 15:01
I said I was going to fix it. It's not fixed yet. I don't want two different issues for the same problem. Follow that issue for updates.
